$METAJSON_TEMP_FOLDERNAME = '.MetaJSON-temp'
$XCRESULT_DIR = 'build/derivedData/Logs/Test'

# Environmental variables keys
$SMF_CHANGELOG_ENV_HTML_KEY = 'SMF_CHANGELOG_HTML'
$SMF_CHANGELOG_EMAILS_ENV_KEY = 'SMF_CHANGELOG_EMAILS'
$SMF_GITHUB_TOKEN_ENV_KEY = 'GITHUB_TOKEN'
$SMF_METADB_API_CREDENTIALS = 'METADB_API_CREDENTIALS'
$SMF_HOCKEYAPP_API_TOKEN_ENV_KEY = 'HOCKEYAPP_API_TOKEN'
$SMF_APP_HOCKEY_ID_ENV_KEY = 'SMF_APP_HOCKEY_ID'
$SMF_APPCENTER_API_TOKEN_ENV_KEY = 'APPCENTER_API_TOKEN'
$SMF_HIPCHAT_API_TOKEN_ENV_KEY = 'HIPCHAT_API_TOKEN'
$SMF_ONE_SIGNAL_BASIC_AUTH_ENV_KEY = 'SMF_HOCKEYAPP_ONE_SIGNAL_BASIC_AUTH'
$SMF_SLACK_URL = 'SMF_SLACK_URL_IDENTIFIER'
$SMF_DID_RUN_UNIT_TESTS_ENV_KEY = 'SMF_DID_RUN_UNIT_TESTS'
$JIRA_DEV_ACCESS_CREDENTIALS = 'JIRA_TOKEN_FASTLANE_ACCESS'

$JIRA_BASE_URL = 'https://smartmobilefactory.atlassian.net'

$SMF_JENKINS_UI_TEST_USER_USERNAME = 'JENKINS_UI_TEST_USER_USERNAME'
$SMF_JENKINS_UI_TEST_USER_PASSWORD = 'JENKINS_UI_TEST_USER_PASSWORD'
$SMF_UI_TEST_REPORT_NAME_FOR_NOTIFICATIONS = 'SMF_UI_TEST_REPORT_NAME_FOR_NOTIFICATIONS'

$SMF_APPCENTER_WEBHOOK_URL = 'https://us-central1-smf-hub.cloudfunctions.net/appcenter'

$WORKSPACE_ENV_KEY = 'WORKSPACE'

$SMF_IS_KEYCHAIN_ENABLED = 'SMF_IS_KEYCHAIN_ENABLED'
$KEYCHAIN_LOGIN_ENV_KEY = 'LOGIN'
$KEYCHAIN_JENKINS_ENV_KEY = 'JENKINS'

# Path to xcode versions, used for xcode_select and ensure_xcode_version in combination with the projects xcode version
$XCODE_EXECUTABLE_PATH_PREFIX = '/Applications/Xcode-'
$XCODE_EXECUTABLE_PATH_POSTFIX = '.app'
$DEVELOPMENT_DIRECTORY_KEY = 'DEVELOPMENT_DIR'

# Default Slack channel to send logs to
$SMF_CI_IOS_ERROR_LOG = 'ci-ios-error-log'
$SMF_CI_ANDROID_ERROR_LOG = 'ci-android-error-log'
$SMF_CI_FLUTTER_ERROR_LOG = 'ci-flutter-error-log'

# We host our own Sentry server so we need to supply the URL ourselves
$SENTRY_AUTH_TOKEN = 'SENTRY_API_ACCESS_TOKEN'

$DANGER_GITHUB_TOKEN_KEY = 'DANGER_GITHUB_API_TOKEN'

# match
$FASTLANE_MATCH_REPO_URL = 'git@github.com:smartmobilefactory/SMF-iOS-Fastlane-Match.git'
$SMF_FASTLANE_ITC_TEAM_ID_KEY = 'FASTLANE_ITC_TEAM_ID'

$SMF_PHRASE_APP_ACCESS_TOKEN_KEY = 'SMF_PHRASEAPP_ACCESS_TOKEN'
$SMF_PHRASE_APP_CUSTOM_TOKEN_KEY = 'CUSTOM_PHRASE_APP_TOKEN'
$SMF_PHRASE_APP_SCRIPTS_REPO_URL = 'git@github.com:smartmobilefactory/Phraseapp-CI.git'

$CHANGELOG_TEMP_FILE = 'temp_changelog.txt'
$CHANGELOG_TEMP_FILE_HTML = 'temp_changelog.html'

$POD_DEFAULT_VARIANTS = ['patch', 'minor', 'major', 'current', 'breaking', 'internal']

$CATALYST_MAC_BUILD_VARIANT_PREFIX = 'macOS_'

### Reporting ###

# Google Sheets
$REPORTING_GOOGLE_SHEETS_CLIENT_ID_KEY = 'REPORTING_CLIENT_ID'
$REPORTING_GOOGLE_SHEETS_CLIENT_SECRET_KEY = 'REPORTING_CLIENT_SECRET'
$REPORTING_GOOGLE_SHEETS_REFRESH_TOKEN_KEY = 'REPORTING_REFRESH_TOKEN'
$REPORTING_GOOGLE_SHEETS_DOC_ID_KEY = 'REPORTING_SPREADSHEET_ID'
$REPORTING_GOOGLE_SHEETS_SHEET_NAME = 'unit-tests'

### Config.json Keys ###

# Deprecated files/folders in repository
$CONFIG_DEPRECATED_FILES_FOLDERS_IOS = ['.MetaJSON', '.codebeatignore', '.codebeatsettings', '.codeclimate.yml', 'smf.properties']
$CONFIG_DEPRECATED_FILES_FOLDERS_ANDROID = ['.MetaJSON', '.codebeatignore', '.codebeatsettings', 'smf.properties']
$CONFIG_DEPRECATED_FILES_FOLDERS_FLUTTER = ['.MetaJSON', '.codebeatignore', '.codebeatsettings', 'smf.properties']

# Required Config.json/project keys
$CONFIG_REQUIRED_PROJECT_KEYS_IOS = ['xcode_version', 'slack_channel', 'project_name']
$CONFIG_REQUIRED_PROJECT_KEYS_ANDROID = ['slack_channel', 'project_name']
$CONFIG_REQUIRED_PROJECT_KEYS_FLUTTER = ['slack_channel', 'project_name']

# Deprecated Config.json/build_variants
$CONFIG_DEPRECATED_BUILD_VARIANT_KEYS_IOS = ['pr.archive_ipa', 'code_signing_identity']
$CONFIG_DEPRECATED_BUILD_VARIANT_KEYS_ANDROID = []
$CONFIG_DEPRECATED_BUILD_VARIANT_KEYS_FLUTTER = []
